clear all
clc

BD_Treinamento_Alimentador_DFIG_AT
BD_Treinamento_Alimentador_DFIG_BT
BD_Treinamento_Alimentador_DFIG_CT
BD_Treinamento_Alimentador_DFIG_ABT
BD_Treinamento_Alimentador_DFIG_BCT
BD_Treinamento_Alimentador_DFIG_CAT
BD_Treinamento_Alimentador_DFIG_AB
BD_Treinamento_Alimentador_DFIG_BC
BD_Treinamento_Alimentador_DFIG_CA
BD_Treinamento_Alimentador_DFIG_ABC

BD_Teste_Completo_Alimentador_DFIG_AT
BD_Teste_Completo_Alimentador_DFIG_BT
BD_Teste_Completo_Alimentador_DFIG_CT
BD_Teste_Completo_Alimentador_DFIG_ABT
BD_Teste_Completo_Alimentador_DFIG_BCT
BD_Teste_Completo_Alimentador_DFIG_CAT
BD_Teste_Completo_Alimentador_DFIG_AB
BD_Teste_Completo_Alimentador_DFIG_BC
BD_Teste_Completo_Alimentador_DFIG_CA
BD_Teste_Completo_Alimentador_DFIG_ABC


disp('Cálculo Finalizado com Éxito...')