clear all
clc

BD_Treinamento_Ramal_9_PMSG_AT
BD_Treinamento_Ramal_9_PMSG_BT
BD_Treinamento_Ramal_9_PMSG_CT
BD_Treinamento_Ramal_9_PMSG_ABT
BD_Treinamento_Ramal_9_PMSG_BCT
BD_Treinamento_Ramal_9_PMSG_CAT
BD_Treinamento_Ramal_9_PMSG_AB
BD_Treinamento_Ramal_9_PMSG_BC
BD_Treinamento_Ramal_9_PMSG_CA
BD_Treinamento_Ramal_9_PMSG_ABC

BD_Teste_Completo_Ramal_9_PMSG_AT
BD_Teste_Completo_Ramal_9_PMSG_BT
BD_Teste_Completo_Ramal_9_PMSG_CT
BD_Teste_Completo_Ramal_9_PMSG_ABT
BD_Teste_Completo_Ramal_9_PMSG_BCT
BD_Teste_Completo_Ramal_9_PMSG_CAT
BD_Teste_Completo_Ramal_9_PMSG_AB
BD_Teste_Completo_Ramal_9_PMSG_BC
BD_Teste_Completo_Ramal_9_PMSG_CA
BD_Teste_Completo_Ramal_9_PMSG_ABC

disp('Cálculo Finalizado com Éxito...')